name: trans_intl
description: Lightweight international text translation solution plug-in.
version: 0.0.3
homepage: https://github.com/ZGL520/trans_intl
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: I18nManager
